# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 18:06
from __future__ import unicode_literals

import audio_transcoder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_transcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='was_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='mp3_file',
            field=models.FileField(upload_to=audio_transcoder.models.md5_directory_path),
        ),
    ]
