# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcode_messages', '0002_auto_20170121_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='readed',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
