# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20170701_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
