# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 21:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iip_przest', models.CharField(max_length=255)),
                ('iip_identy', models.CharField(max_length=255)),
                ('iip_wersja', models.CharField(max_length=255)),
                ('jpt_sjr_ko', models.CharField(max_length=255)),
                ('jpt_kod_je', models.CharField(max_length=255)),
                ('jpt_nazwa_field', models.CharField(max_length=255)),
                ('jpt_nazw01', models.CharField(max_length=255)),
                ('jpt_organ_field', models.CharField(max_length=255)),
                ('jpt_orga01', models.CharField(max_length=255)),
                ('jpt_jor_id', models.FloatField()),
                ('wazny_od', models.DateField()),
                ('wazny_do', models.DateField()),
                ('jpt_wazna_field', models.CharField(max_length=255)),
                ('wersja_od', models.DateField()),
                ('wersja_do', models.DateField()),
                ('jpt_powier', models.FloatField()),
                ('jpt_kj_iip', models.CharField(max_length=255)),
                ('jpt_kj_i01', models.CharField(max_length=255)),
                ('jpt_kj_i02', models.CharField(max_length=255)),
                ('jpt_kod_01', models.CharField(max_length=255)),
                ('id_bufora_field', models.FloatField()),
                ('id_bufor01', models.FloatField()),
                ('id_technic', models.FloatField()),
                ('jpt_opis', models.CharField(max_length=255)),
                ('jpt_sps_ko', models.CharField(max_length=255)),
                ('gra_ids', models.CharField(max_length=255)),
                ('status_obi', models.CharField(max_length=255)),
                ('opis_bledu', models.CharField(max_length=255)),
                ('typ_bledu', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2180)),
            ],
        ),
    ]
