# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_transcoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='ac3_file',
            new_name='flac_file',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='ogg_file',
            new_name='mp4_file',
        ),
    ]
