# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0004_auto_20170701_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('year', models.DateField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('actors', models.ManyToManyField(to='actors.Actor')),
            ],
        ),
    ]
